from typing import Any
from .core import MagiDict

def enchant(d: Any) -> MagiDict: ...
def magi_load(fp: Any, **kwargs: Any) -> MagiDict: ...
def magi_loads(s: Any, **kwargs: Any) -> MagiDict: ...
def none(obj: Any) -> Any: ...